global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: ‘jenkins’
  metrics_path: /prometheus
  scheme: http
  static_configs:
  - targets: [54.159.70.70:8080]
#- job_name: 'EC2'
#ec2_sd_configs:
#- job_name: EC2
#  - region: us-east-1b
#    access_key: AKIAJ3SL4FBJM5IET6QQ
#    secret_key: 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


- job_name: 'node'
  ec2_sd_configs:
    - region: us-east-1
      access_key: AKIAJ3SL4FBJM5IET6QQ
      secret_key: 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
      port: 9100

- job_name: 'docker'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

  static_configs:
    - targets: ['54.159.70.70:90']
